-- BAGOUÉ 360 : ordre du jour des séances et demandes de parole.
--
-- FICHIER GÉNÉRÉ — ne pas modifier à la main.
-- Source : web/src/mocks/dataset.ts · Régénérer : cd web && npm run seed:sql
--
-- Séparé de V2 parce que les tables visées naissent en V3.
INSERT INTO point_ordre_du_jour (id, session_id, ordre, intitule, rapporteur, statut, projet_id, programme_id, duree_prevue_min, pour, contre, abstention, deliberation) VALUES
  ('pdj-ses-1-1', 'ses-1', 1, 'Attribution du marché — Magasins de stockage céréalier', 'Silué Awa', 'A_EXAMINER', NULL, 'prg-14', 15, NULL, NULL, NULL, NULL),
  ('pdj-ses-1-2', 'ses-1', 2, 'Convention de partenariat — Construction d’un foyer des jeunes à Débété', 'Koné Sékou', 'A_EXAMINER', 'prj-103', NULL, 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-1-3', 'ses-1', 3, 'Autorisation de programme', 'Coulibaly Mariam', 'A_EXAMINER', NULL, NULL, 15, NULL, NULL, NULL, NULL),
  ('pdj-ses-1-4', 'ses-1', 4, 'Adoption du procès-verbal de la séance précédente', 'Doumbia Yacouba', 'A_EXAMINER', NULL, NULL, 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-1-5', 'ses-1', 5, 'Attribution du marché — Construction de salles de classe', 'Koné Sékou', 'A_EXAMINER', NULL, 'prg-2', 15, NULL, NULL, NULL, NULL),
  ('pdj-ses-1-6', 'ses-1', 6, 'Autorisation de programme — Hydraulique villageoise améliorée', 'Silué Ibrahim', 'A_EXAMINER', NULL, 'prg-1', 20, NULL, NULL, NULL, NULL),
  ('pdj-ses-1-7', 'ses-1', 7, 'Affectation budgétaire complémentaire — Ouverture de 16 km de pistes rurales autour de Kasséré', 'Bamba Lassina', 'A_EXAMINER', 'prj-4', NULL, 30, NULL, NULL, NULL, NULL),
  ('pdj-ses-2-1', 'ses-2', 1, 'Autorisation de programme — Réhabilitation de 7 points d’eau à Kanakono', 'Soro Fatoumata', 'ADOPTE', 'prj-65', NULL, 15, 26, 13, 2, 'DÉL-2026-008'),
  ('pdj-ses-2-2', 'ses-2', 2, 'Autorisation de programme — Construction de salles de classe', 'Soro Sékou', 'ADOPTE', NULL, 'prg-2', 20, 29, 6, 6, 'DÉL-2026-009'),
  ('pdj-ses-2-3', 'ses-2', 3, 'Réception définitive des ouvrages — Construction d’un foyer des jeunes à Boundiali', 'Koné Adama', 'ADOPTE', 'prj-79', NULL, 10, 26, 13, 2, 'DÉL-2026-010'),
  ('pdj-ses-2-4', 'ses-2', 4, 'Adoption du procès-verbal de la séance précédente', 'Touré Lassina', 'REJETE', NULL, NULL, 45, 7, 31, 3, NULL),
  ('pdj-ses-2-5', 'ses-2', 5, 'Approbation du plan annuel d’investissement — Maternités rurales', 'Coulibaly Lassina', 'REJETE', NULL, 'prg-12', 30, 10, 31, 0, NULL),
  ('pdj-ses-2-6', 'ses-2', 6, 'Convention de partenariat — Aménagement de 17 hectares maraîchers à Blességué', 'Ouattara Sékou', 'ADOPTE', 'prj-101', NULL, 15, 31, 10, 0, 'DÉL-2026-013'),
  ('pdj-ses-3-1', 'ses-3', 1, 'Affectation budgétaire complémentaire — Réhabilitation du groupe scolaire de Kanakono', 'Touré Awa', 'A_EXAMINER', 'prj-130', NULL, 15, NULL, NULL, NULL, NULL),
  ('pdj-ses-3-2', 'ses-3', 2, 'Attribution du marché — Réhabilitation de 15 points d’eau à Kolia', 'Diomandé Sékou', 'A_EXAMINER', 'prj-97', NULL, 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-3-3', 'ses-3', 3, 'Attribution du marché — Réhabilitation de la maternité de Tengréla', 'Bamba Nadège', 'A_EXAMINER', 'prj-115', NULL, 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-3-4', 'ses-3', 4, 'Attribution du marché', 'Silué Mariam', 'A_EXAMINER', NULL, NULL, 45, NULL, NULL, NULL, NULL),
  ('pdj-ses-3-5', 'ses-3', 5, 'Autorisation de programme — Réhabilitation de 14 points d’eau à Débété', 'Coulibaly Fatoumata', 'A_EXAMINER', 'prj-25', NULL, 30, NULL, NULL, NULL, NULL),
  ('pdj-ses-3-6', 'ses-3', 6, 'Autorisation de programme — Équipement du centre de formation de Kouto', 'Touré Ibrahim', 'A_EXAMINER', 'prj-7', NULL, 20, NULL, NULL, NULL, NULL),
  ('pdj-ses-3-7', 'ses-3', 7, 'Attribution du marché — Réhabilitation de la maternité de Ganaoni', 'Silué Yacouba', 'A_EXAMINER', 'prj-3', NULL, 45, NULL, NULL, NULL, NULL),
  ('pdj-ses-4-1', 'ses-4', 1, 'Réception définitive des ouvrages — Ouverture de 5 km de pistes rurales autour de Boundiali', 'Silué Yacouba', 'A_EXAMINER', 'prj-92', NULL, 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-4-2', 'ses-4', 2, 'Autorisation de programme — Équipement du centre de formation de Ganaoni', 'Doumbia Awa', 'A_EXAMINER', 'prj-55', NULL, 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-4-3', 'ses-4', 3, 'Approbation du plan annuel d’investissement — Équipements marchands de proximité', 'Ouattara Lassina', 'A_EXAMINER', NULL, 'prg-9', 15, NULL, NULL, NULL, NULL),
  ('pdj-ses-4-4', 'ses-4', 4, 'Approbation du plan annuel d’investissement — Construction de salles de classe', 'Soro Mariam', 'A_EXAMINER', NULL, 'prg-2', 30, NULL, NULL, NULL, NULL),
  ('pdj-ses-4-5', 'ses-4', 5, 'Affectation budgétaire complémentaire — Construction d’un dépotoir contrôlé à Kanakono', 'Bamba Sékou', 'A_EXAMINER', 'prj-104', NULL, 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-4-6', 'ses-4', 6, 'Autorisation de programme — Équipements marchands de proximité', 'Diomandé Adama', 'A_EXAMINER', NULL, 'prg-9', 15, NULL, NULL, NULL, NULL),
  ('pdj-ses-5-1', 'ses-5', 1, 'Autorisation de programme — Équipement du centre de santé rural de Gbon', 'Koné Awa', 'ADOPTE', 'prj-99', NULL, 20, 21, 4, 0, 'DÉL-2024-027'),
  ('pdj-ses-5-2', 'ses-5', 2, 'Attribution du marché — Pistes rurales et ouvrages de franchissement', 'Coulibaly Yacouba', 'ADOPTE', NULL, 'prg-4', 30, 16, 4, 5, 'DÉL-2024-028'),
  ('pdj-ses-5-3', 'ses-5', 3, 'Convention de partenariat — Extension du réseau électrique de Kasséré', 'Koné Lassina', 'ADOPTE', 'prj-30', NULL, 20, 11, 9, 5, 'DÉL-2024-029'),
  ('pdj-ses-5-4', 'ses-5', 4, 'Affectation budgétaire complémentaire — Construction de 14 forages équipés de pompes à motricité humaine', 'Coulibaly Lassina', 'ADOPTE', 'prj-49', NULL, 10, 19, 4, 2, 'DÉL-2024-030'),
  ('pdj-ses-6-1', 'ses-6', 1, 'Approbation du plan annuel d’investissement — Reprofilage des pistes cotonnières', 'Diomandé Yacouba', 'A_EXAMINER', NULL, 'prg-13', 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-6-2', 'ses-6', 2, 'Convention de partenariat', 'Bamba Fatoumata', 'A_EXAMINER', NULL, NULL, 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-6-3', 'ses-6', 3, 'Convention de partenariat — Réhabilitation de la maternité de Ganaoni', 'Doumbia Sékou', 'A_EXAMINER', 'prj-3', NULL, 30, NULL, NULL, NULL, NULL),
  ('pdj-ses-6-4', 'ses-6', 4, 'Attribution du marché — Cantines scolaires régionales', 'Ouattara Sékou', 'A_EXAMINER', NULL, 'prg-11', 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-6-5', 'ses-6', 5, 'Autorisation de programme — Construction d’un ouvrage de franchissement à Baya', 'Touré Mariam', 'A_EXAMINER', 'prj-132', NULL, 20, NULL, NULL, NULL, NULL),
  ('pdj-ses-7-1', 'ses-7', 1, 'Réception définitive des ouvrages — Réhabilitation du groupe scolaire de Baya', 'Diomandé Ibrahim', 'REJETE', 'prj-106', NULL, 15, 11, 24, 0, NULL),
  ('pdj-ses-7-2', 'ses-7', 2, 'Affectation budgétaire complémentaire — Réhabilitation du groupe scolaire de Baya', 'Touré Awa', 'REJETE', 'prj-2', NULL, 20, 3, 29, 3, NULL),
  ('pdj-ses-7-3', 'ses-7', 3, 'Réception définitive des ouvrages — Extension du réseau électrique de Sianhala', 'Koné Fatoumata', 'ADOPTE', 'prj-126', NULL, 45, 25, 6, 4, 'DÉL-2025-038'),
  ('pdj-ses-7-4', 'ses-7', 4, 'Attribution du marché — Électrification solaire du centre de santé de Siempurgo', 'Silué Nadège', 'REPORTE', 'prj-70', NULL, 20, NULL, NULL, NULL, NULL),
  ('pdj-ses-7-5', 'ses-7', 5, 'Convention de partenariat — Réhabilitation du groupe scolaire de Kanakono', 'Ouattara Awa', 'REJETE', 'prj-130', NULL, 15, 2, 28, 5, NULL),
  ('pdj-ses-7-6', 'ses-7', 6, 'Convention de partenariat — Équipement du centre de santé rural de Boundiali', 'Koné Mariam', 'ADOPTE', 'prj-27', NULL, 30, 23, 11, 1, 'DÉL-2025-041'),
  ('pdj-ses-7-7', 'ses-7', 7, 'Autorisation de programme', 'Koné Mariam', 'ADOPTE', NULL, NULL, 30, 17, 15, 3, 'DÉL-2025-042'),
  ('pdj-ses-8-1', 'ses-8', 1, 'Autorisation de programme — Électrification rurale décentralisée', 'Ouattara Adama', 'EN_DISCUSSION', NULL, 'prg-6', 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-8-2', 'ses-8', 2, 'Approbation du plan annuel d’investissement — Hydraulique villageoise améliorée', 'Ouattara Adama', 'A_EXAMINER', NULL, 'prg-1', 30, NULL, NULL, NULL, NULL),
  ('pdj-ses-8-3', 'ses-8', 3, 'Convention de partenariat — Réhabilitation de la maternité de Kolia', 'Koné Yacouba', 'A_EXAMINER', 'prj-19', NULL, 45, NULL, NULL, NULL, NULL),
  ('pdj-ses-9-1', 'ses-9', 1, 'Approbation du plan annuel d’investissement — Équipements marchands de proximité', 'Coulibaly Fatoumata', 'ADOPTE', NULL, 'prg-9', 10, 19, 2, 2, 'DÉL-2026-046'),
  ('pdj-ses-9-2', 'ses-9', 2, 'Attribution du marché — Construction d’un foyer des jeunes à Baya', 'Koné Fatoumata', 'REJETE', 'prj-15', NULL, 15, 5, 14, 4, NULL),
  ('pdj-ses-9-3', 'ses-9', 3, 'Convention de partenariat — Extension du réseau électrique de Boundiali', 'Koné Sékou', 'EN_DISCUSSION', 'prj-14', NULL, 15, NULL, NULL, NULL, NULL),
  ('pdj-ses-9-4', 'ses-9', 4, 'Attribution du marché — Aménagement d’un bas-fond rizicole à Gbon', 'Diomandé Fatoumata', 'A_EXAMINER', 'prj-125', NULL, 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-9-5', 'ses-9', 5, 'Attribution du marché — Construction d’un foyer des jeunes à Baya', 'Diomandé Adama', 'A_EXAMINER', 'prj-15', NULL, 20, NULL, NULL, NULL, NULL),
  ('pdj-ses-10-1', 'ses-10', 1, 'Attribution du marché — Réhabilitation du groupe scolaire de Kanakono', 'Diomandé Adama', 'ADOPTE', 'prj-130', NULL, 45, 26, 10, 0, 'DÉL-2026-051'),
  ('pdj-ses-10-2', 'ses-10', 2, 'Approbation du plan annuel d’investissement — Adduction d’eau potable de Kouto', 'Coulibaly Sékou', 'ADOPTE', NULL, 'prg-10', 30, 17, 14, 5, 'DÉL-2026-052'),
  ('pdj-ses-10-3', 'ses-10', 3, 'Affectation budgétaire complémentaire — Réhabilitation de 15 points d’eau à Kolia', 'Ouattara Adama', 'ADOPTE', 'prj-97', NULL, 30, 22, 12, 2, 'DÉL-2026-053'),
  ('pdj-ses-10-4', 'ses-10', 4, 'Attribution du marché', 'Ouattara Sékou', 'REPORTE', NULL, NULL, 30, NULL, NULL, NULL, NULL),
  ('pdj-ses-10-5', 'ses-10', 5, 'Autorisation de programme — Équipements marchands de proximité', 'Koné Fatoumata', 'VOTE_EN_COURS', NULL, 'prg-9', 15, NULL, NULL, NULL, NULL),
  ('pdj-ses-11-1', 'ses-11', 1, 'Attribution du marché — Réhabilitation de la maternité de Kanakono', 'Ouattara Ibrahim', 'A_EXAMINER', 'prj-91', NULL, 30, NULL, NULL, NULL, NULL),
  ('pdj-ses-11-2', 'ses-11', 2, 'Affectation budgétaire complémentaire — Aménagement du terrain de sport de Sianhala', 'Coulibaly Nadège', 'A_EXAMINER', 'prj-87', NULL, 30, NULL, NULL, NULL, NULL),
  ('pdj-ses-11-3', 'ses-11', 3, 'Autorisation de programme', 'Diomandé Awa', 'A_EXAMINER', NULL, NULL, 20, NULL, NULL, NULL, NULL),
  ('pdj-ses-12-1', 'ses-12', 1, 'Approbation du plan annuel d’investissement — Magasins de stockage céréalier', 'Ouattara Lassina', 'ADOPTE', NULL, 'prg-14', 10, 18, 11, 0, 'DÉL-2024-059'),
  ('pdj-ses-12-2', 'ses-12', 2, 'Attribution du marché — Construction de 15 forages équipés de pompes à motricité humaine', 'Coulibaly Awa', 'VOTE_EN_COURS', 'prj-73', NULL, 20, NULL, NULL, NULL, NULL),
  ('pdj-ses-12-3', 'ses-12', 3, 'Attribution du marché — Construction d’un magasin de stockage à Siempurgo', 'Doumbia Yacouba', 'A_EXAMINER', 'prj-5', NULL, 45, NULL, NULL, NULL, NULL),
  ('pdj-ses-12-4', 'ses-12', 4, 'Attribution du marché — Construction de salles de classe', 'Touré Sékou', 'A_EXAMINER', NULL, 'prg-2', 45, NULL, NULL, NULL, NULL),
  ('pdj-ses-13-1', 'ses-13', 1, 'Autorisation de programme — Aménagement de 17 hectares maraîchers à Baya', 'Diomandé Yacouba', 'A_EXAMINER', 'prj-93', NULL, 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-13-2', 'ses-13', 2, 'Affectation budgétaire complémentaire — Construction d’un foyer des jeunes à Boundiali', 'Soro Ibrahim', 'A_EXAMINER', 'prj-79', NULL, 45, NULL, NULL, NULL, NULL),
  ('pdj-ses-13-3', 'ses-13', 3, 'Attribution du marché', 'Soro Nadège', 'A_EXAMINER', NULL, NULL, 45, NULL, NULL, NULL, NULL),
  ('pdj-ses-13-4', 'ses-13', 4, 'Convention de partenariat — Réhabilitation de 17 points d’eau à Kasséré', 'Diomandé Ibrahim', 'A_EXAMINER', 'prj-121', NULL, 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-13-5', 'ses-13', 5, 'Réception définitive des ouvrages — Ouverture de 4 km de pistes rurales autour de Blességué', 'Koné Fatoumata', 'A_EXAMINER', 'prj-36', NULL, 20, NULL, NULL, NULL, NULL),
  ('pdj-ses-13-6', 'ses-13', 6, 'Affectation budgétaire complémentaire', 'Diomandé Awa', 'A_EXAMINER', NULL, NULL, 10, NULL, NULL, NULL, NULL),
  ('pdj-ses-14-1', 'ses-14', 1, 'Affectation budgétaire complémentaire — Construction de 2 salles de classe à Kolia', 'Touré Sékou', 'ADOPTE', 'prj-58', NULL, 20, 32, 3, 5, 'DÉL-2026-069'),
  ('pdj-ses-14-2', 'ses-14', 2, 'Attribution du marché — Reprofilage des pistes cotonnières', 'Diomandé Fatoumata', 'REPORTE', NULL, 'prg-13', 15, NULL, NULL, NULL, NULL),
  ('pdj-ses-14-3', 'ses-14', 3, 'Affectation budgétaire complémentaire — Réalisation de 3 latrines scolaires à Tengréla', 'Bamba Fatoumata', 'REJETE', 'prj-128', NULL, 30, 6, 33, 1, NULL);

INSERT INTO demande_parole (id, session_id, point_id, demandeur, fonction, demandee_a, statut) VALUES
  ('parl-ses-9-1', 'ses-9', 'pdj-ses-9-3', 'Ouattara Fatoumata', 'Directeur technique', '09:19', 'ACCORDEE'),
  ('parl-ses-9-2', 'ses-9', 'pdj-ses-9-3', 'Yéo Mariam', 'Président de commission', '13:55', 'EN_ATTENTE'),
  ('parl-ses-9-3', 'ses-9', 'pdj-ses-9-3', 'Koné Lassina', 'Vice-président', '15:11', 'EN_ATTENTE'),
  ('parl-ses-9-4', 'ses-9', 'pdj-ses-9-3', 'Touré Ibrahim', 'Conseiller régional', '12:04', 'EN_ATTENTE'),
  ('parl-ses-10-1', 'ses-10', 'pdj-ses-10-5', 'Touré Lassina', 'Conseiller régional', '15:01', 'ACCORDEE'),
  ('parl-ses-10-2', 'ses-10', 'pdj-ses-10-5', 'Soro Yacouba', 'Vice-président', '13:56', 'ECOULEE'),
  ('parl-ses-10-3', 'ses-10', 'pdj-ses-10-5', 'Doumbia Nadège', 'Vice-président', '10:00', 'EN_ATTENTE'),
  ('parl-ses-12-1', 'ses-12', 'pdj-ses-12-2', 'Touré Nadège', 'Conseiller régional', '11:56', 'ACCORDEE');
